# Default values for opsilon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

client:
  replicaCount: 1
  image:
    repository: jatalocks333/opsilon-web
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    annotations: {}
  env: []
  envSecrets: []
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}

server:
  replicaCount: 1
  image:
    repository: jatalocks333/opsilon
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    annotations: {}
  env: []
  envSecrets: []
  annotations: {}    
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - opsilon.my.domain
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

mongodb:
  persistence:
    enabled: true
  architecture: replicaset
  replicaCount: 2
  auth:
    enabled: false
    # usernames: 
    #   - user
    # passwords: 
    #   - password
    # databases: 
    #   - opsilon
