actions:
  - name: Create namespace
    help: Creates a namespace
    args:
      - branch: string
      - namespace: string
  - name: Delete namespace
    help: deletes a namespace
    args:
      - namespace: string