actions:
  - name: Create namespace
    help: Creates a namespace
    args:
      - name: branch
        type: string
        default: main
      - name: namespace
        type: string
        optional: false
  - name: Delete namespace
    help: deletes a namespace
    args:
      - name: namespace
        type: string