# ID of job to match an action in the actions file
id: example
# Help Description
description: this is an example workflow which includes all of opsilon capabilities

# Global Docker Image
image: alpine:latest

# Global Environment Variables
env:
  - name: filename
    value: testValue

input:
  - name: arg1
    default: defaultvalue
  - name: arg2
  - name: arg3
    optional: true

stages:
  - stage: write a file 1
    id: writefile
    image: ubuntu:latest
    env:
      - name: test
        value: hi
    if: $arg3 != ""
    script:
      - sh
      - -c
      - |
        echo hi
        echo "arg4=runme" >> $OUTPUT
        mkdir testdir1 && echo $arg3 >> testdir1/test.txt
    artifacts:
      - testdir1
      - test.txt # will not exist
  - stage: write a file 2
    id: writefile2
    needs: writefile # will get the outputs of the stage with this ID
    clean: true # this stage will not share a filesystem with the other stages. It will start with a clean /app as working directory.
    if: $arg4 == "runme"
    script:
      - sh
      - -c
      - mkdir testdir2 && echo $arg4 >> testdir2/test.txt && ls -l
    artifacts:
      - testdir2
      - testdir2/test.txt
  - stage: read the file
    id: readfile
    script:
      - sh
      - -c
      - ls -l && cat test.txt
  - stage: just a random step
    id: testme
    needs: writefile2
    script:
      - sh
      - -c
      - ls -l && cat test.txt
  - stage: just a random step
    id: testme2
    needs: writefile2
    script:
      - sh
      - -c
      - ls -l && cat test.txt            