# ID of job to match an action in the actions file
id: example
# Help Description
description: this is an example workflow which includes all of opsilon capabilities

# Global Docker Image
image: alpine:latest

# Global Environment Variables
env:
  - name: filename
    value: testValue

input:
  - name: arg1
    default: defaultvalue
  - name: arg2
  - name: arg3
    optional: true

stages:
  - stage: write a file 1
    id: writefile
    image: ubuntu:latest
    if: $arg3 != ""
    script:
      - sh
      - -c
      - |
        echo hi
        echo "arg4=runme" >> $OUTPUT
        mkdir testdir1 && echo $arg3 >> testdir1/test.txt
    artifacts:
      - testdir1
      - test.txt # will not exist
  - stage: write a file 2
    needs: writefile
    if: $arg4 == "runme"
    script:
      - sh
      - -c
      - mkdir testdir2 && echo $arg2 >> testdir2/test.txt
    artifacts:
      - testdir2
      - testdir2/test.txt
  - stage: read the file
    script:
      - sh
      - -c
      - ls -l && cat test.txt