apiVersion: v1
kind: Service
metadata:
  name: {{ template "opsilon.name" . }}-client
{{- with .Values.client.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}  
{{- end }}    
  labels:
    app: {{ template "opsilon.name" . }}-client
    chart: {{ template "opsilon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - name: http
      port: {{ .Values.client.service.port | default 80 }}
      targetPort: 80
  selector:
    app: {{ template "opsilon.name" . }}-client
    release: {{ .Release.Name }}
