apiVersion: v1
kind: Service
metadata:
  name: {{ template "opsilon.name" . }}-server
  labels:
    app: {{ template "opsilon.name" . }}-server
    chart: {{ template "opsilon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.server.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}    
{{- end }}   
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "opsilon.name" . }}-server
    release: {{ .Release.Name }}
  
